name: Build and deploy Node.js app to Linux VM - cmu313-s25

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # lint-and-test:
  #   uses:
  #     ./.github/workflows/test.yaml

  build-and-deploy:
    if: github.repository == 'cmu-313/nodebb-s25-test-mones' #should be editted to repo name
    # needs: lint-and-test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Set up NodeBB
        run: |
          ./nodebb setup '{"url":"${{ secrets.SERVER_IP }}:443",
            "admin:username": "${{ secrets.SERVER_USER }}",
            "admin:password": "${{ secrets.ADMIN_PASSWORD }}",
            "admin:password:confirm": "${{ secrets.ADMIN_PASSWORD }}",
            "admin:email": "mhilton@cmu.edu",
            "database": "redis",
            "redis:host": "${{ secrets.SERVER_IP }}",
            "redis:port": "6379",
            "redis:password": "" }'
          
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # may not need the npm install command
          script: | 
            git pull origin main
            npm install --production
            sudo systemctl restart nodebb
